# permissions for end users to edit kafkawrappers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: kafkawrapper-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sample-go-operator
    app.kubernetes.io/part-of: sample-go-operator
    app.kubernetes.io/managed-by: kustomize
  name: kafkawrapper-editor-role
rules:
- apiGroups:
  - kafka-wrapper.sample.com
  resources:
  - kafkawrappers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kafka-wrapper.sample.com
  resources:
  - kafkawrappers/status
  verbs:
  - get
