apiVersion: kafka-wrapper.sample.com/v1alpha1
kind: KafkaWrapper
metadata:
  labels:
    app.kubernetes.io/name: kafkawrapper
    app.kubernetes.io/instance: kafkawrapper-sample
    app.kubernetes.io/part-of: sample-go-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sample-go-operator
  name: kafkawrapper-sample
spec:
  # TODO(user): Add fields here
